### ISSUE TITLE
Problem with virtual ruby

### ISSUE THREAD

**Issue by IsmaelFraga** [Beagle123/visualruby#43]
Hi. I had installed VR on my Windows 7 PRO 64. All goes ok, but when I tried to execute VR I had some messages. Could you to help me?

Messages received:

C:\Users\NETOS>vr
C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
: cannot load such file -- cairo.so (LoadError)
        from C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55
:in `require'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cairo-1.15.5-x64-mingw32/lib
/cairo.rb:48:in `rescue in <top (required)>'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cairo-1.15.5-x64-mingw32/lib
/cairo.rb:44:in `<top (required)>'
        from C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55
:in `require'
        from C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55
:in `require'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/glib2-3.1.1-x64-mingw32/lib/
glib2.rb:112:in `<top (required)>'
        from C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55
:in `require'
        from C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55
:in `require'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/gobject-introspection-3.1.1-
x64-mingw32/lib/gobject-introspection.rb:17:in `<top (required)>'
        from C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55
:in `require'
        from C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55
:in `require'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/gtk3-3.1.1-x64-mingw32/lib/g
tk3.rb:17:in `<top (required)>'
        from C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55
:in `require'
        from C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55
:in `require'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/visualruby-3.1.7/vr:1:in `<t
op (required)>'
        from C:/Ruby24-x64/bin/vr:22:in `load'
        from C:/Ruby24-x64/bin/vr:22:in `<main>'

Thanks.

**Comment by Beagle123** [comment]
Hi:

Try manually installing the cairo library.  I don't have a windows machine, so I can't reproduce that error.  I forget what package cairo belongs to, but try installing it again.

**Comment by Beagle123** [comment]
try:

gem install cairo

**Comment by IsmaelFraga** [comment]
Thanks Beagle123, but the problem persist. Do you have another sugestion?
I changed my window PATH early, but does'nt work.

**Comment by rubycoder** [comment]
Hi Ismael,

I'm running VR on Win 7 Pro SP1 64 bit.

However, I'm running Ruby 2.3.1 32 bit:

	C:\>ruby -v
	ruby 2.3.1p112 (2016-04-26 revision 54768) [i386-mingw32]

Through a lot of trial and error (with many gems, not just VR) I've found that trying to run the latest version of Ruby (that is, 2.4.x) on Windows is just too difficult, as the Windows versions of many gems don't get updated promptly.

The RubyInstaller page, https://rubyinstaller.org/downloads/ , recommends 2.2.x for just this reason.

I've also had problems with 64 bit Ruby on Windows.  The above RubyInstaller page used to recommend against 64 bit, but it looks like they removed that warning from the current page.

Could you try installing a 32 bit Ruby, either 2.2.x or 2.3.x to see if that resolves this issue?

Good luck,

Wayne

**Comment by rubycoder** [comment]
P.S. I think there were some issues with VR and 2.2.x, so I'd try 2.3.x

**Comment by Beagle123** [comment]
Thanks Wayne.  

Ismael, let me know if it fixes it.

**Comment by IsmaelFraga** [comment]
Thanks a lot for all!! I installed the sugested version (2.3) and all goes ok. See you...

**Comment by rubycoder** [comment]
Great!  Glad to hear it.

Out of curiosity, did you use 64 bit or 32 bit?
