### ISSUE TITLE
Windows 10 x64 regular and bash run error

### ISSUE THREAD

**Issue by PaladinNW** [Beagle123/visualruby#47]
After trying to resolve this with google, previous issues, and downloading probably way too many gems and libraries I'm hoping you can help. every time I run vr, I get this error:
`Traceback (most recent call last):
        15: from /home/paladin/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:15:in `<main>'
        14: from /home/paladin/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:15:in `eval'
        13: from /home/paladin/.rvm/gems/ruby-2.5.1/bin/vr:23:in `<main>'
        12: from /home/paladin/.rvm/gems/ruby-2.5.1/bin/vr:23:in `load'
        11: from /home/paladin/.rvm/gems/ruby-2.5.1/gems/visualruby-3.1.11/vr:44:in `<top (required)>'
        10: from /home/paladin/.rvm/gems/ruby-2.5.1/gems/gobject-introspection-3.1.1/lib/gobject-introspection/loader.rb:110:in `block in define_singleton_method'
         9: from /home/paladin/.rvm/gems/ruby-2.5.1/gems/gobject-introspection-3.1.1/lib/gobject-introspection/loader.rb:110:in `invoke'
         8: from /home/paladin/.rvm/gems/ruby-2.5.1/gems/visualruby-3.1.11/vr:41:in `block in <top (required)>'
         7: from /home/paladin/.rvm/gems/ruby-2.5.1/gems/visualruby-3.1.11/vr:17:in `load_everything'
         6: from /home/paladin/.rvm/gems/ruby-2.5.1/gems/require_all-2.0.0/lib/require_all.rb:117:in `require_rel'
         5: from /home/paladin/.rvm/gems/ruby-2.5.1/gems/require_all-2.0.0/lib/require_all.rb:117:in `each'
         4: from /home/paladin/.rvm/gems/ruby-2.5.1/gems/require_all-2.0.0/lib/require_all.rb:118:in `block in require_rel'
         3: from /home/paladin/.rvm/gems/ruby-2.5.1/gems/require_all-2.0.0/lib/require_all.rb:96:in `require_all'
         2: from /home/paladin/.rvm/gems/ruby-2.5.1/gems/require_all-2.0.0/lib/require_all.rb:96:in `each'
         1: from /home/paladin/.rvm/gems/ruby-2.5.1/gems/require_all-2.0.0/lib/require_all.rb:97:in `block in require_all'
/home/paladin/.rvm/gems/ruby-2.5.1/gems/require_all-2.0.0/lib/require_all.rb:102:in `rescue in block in require_all': Could not require /home/paladin/.rvm/gems/ruby-2.5.1/gems/visualruby-3.1.11/lib/Alert.rb (**uninitialized constant VR::Alert::GladeGUI**). Please require the necessary files (RequireAll::LoadError)` I'm pretty sure I'm just blind and this is a simple fix but I've tried tweaking almost everything. 
 I'm running Windows 10 x64 with Ubuntu for windows. Now I can run graphical Apps just fine with the use of xming Server on the windows side, and can even run Glade on it's own by executing it through the ubuntu bash side, but I cannot get visualruby to work. I get a splashscreen and then this error. I'm running rvm on ruby2.5.1 but I also receive the error running on 2.4.x installs. I get this same error even running vr through just regular Windows cmd. Any ideas? Thank you for your time.

**Comment by KDGundermann** [comment]
Please have a look at #43 :  Use Ruby 2.3 on Windows

**Comment by PaladinNW** [comment]
Thanks but that seems not to work either. Still the exact same error.

**Comment by PaladinNW** [comment]
I got it! It was the  Require_All gem. The most current is Require_All-2.0.0 but VisualRuby requires require_all greater than 1.2. So I uninstalled the gem and installed 1.2 because it was one of the last things I could have possibly done. It finally works!

**Comment by Beagle123** [comment]
Yes that's right.  I just fixed it.  just install the latest visualruby gem.
