### ISSUE TITLE
visual ruby load error

### ISSUE THREAD

**Issue by BartokFan** [Beagle123/visualruby#49]
i am trying to load vr on windows 10.  when trying to start vr i get uninstalled constant VR::Alert::GladeGUI
i have down loaded the latest version but can not get past this error.
thanks for any help you can give.

**Comment by Beagle123** [comment]
Hi:

Thanks for bringing this to my attention.  I've updated the visualruby gem to v 3.2.2  This will fix the problem.  Just do this:

gem install visualruby

Thanks,
Eric

**Comment by BartokFan** [comment]
Thanks Eric.  After installing the gem I get another error.

 

Thanks so much for your help, as well as all the work that went into vr.

Evan

 

C:\Ruby23\bin>ruby gem install visualruby

Fetching: require_all-1.4.0.gem (100%)

Successfully installed require_all-1.4.0

Fetching: visualruby-3.2.2.gem (100%)

Successfully installed visualruby-3.2.2

Parsing documentation for require_all-1.4.0

Installing ri documentation for require_all-1.4.0

Parsing documentation for visualruby-3.2.2

Installing ri documentation for visualruby-3.2.2

Done installing documentation for require_all, visualruby after 1 seconds

2 gems installed

 

C:\Ruby23\bin>vr

C:/Ruby23/lib/ruby/gems/2.3.0/gems/require_all-2.0.0/lib/require_all.rb:102:in `rescue in block in require_all': Could not require C:/Ruby23/lib/ruby/gems/2.3.0/gems/visualruby-3.2.2/lib/oinspect/MethodsListView.rb (uninitialized constant VR::ListView). Please require the necessary files (RequireAll::LoadError)

        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/require_all-2.0.0/lib/require_all.rb:97:in `block in require_all'

        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/require_all-2.0.0/lib/require_all.rb:96:in `each'

        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/require_all-2.0.0/lib/require_all.rb:96:in `require_all'

        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/require_all-2.0.0/lib/require_all.rb:118:in `block in require_rel'

        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/require_all-2.0.0/lib/require_all.rb:117:in `each'

        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/require_all-2.0.0/lib/require_all.rb:117:in `require_rel'

        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/visualruby-3.2.2/vr:20:in `load_everything'

        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/visualruby-3.2.2/vr:44:in `block in <top (required)>'

        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/gobject-introspection-3.2.5-x86-mingw32/lib/gobject-introspection/loader.rb:110:in `invoke'

        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/gobject-introspection-3.2.5-x86-mingw32/lib/gobject-introspection/loader.rb:110:in `block in define_singleton_method'

        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/visualruby-3.2.2/vr:47:in `<top (required)>'

        from C:/Ruby23/bin/vr:22:in `load'

        from C:/Ruby23/bin/vr:22:in `<main>'

 

C:\Ruby23\bin>

**Comment by Beagle123** [comment]
Sorry for delay.  This problem is the same as before.  Try updating to latest version vr v2.2.3 and see if it fixes it.  It should force it to use the older requier_all gem v1.4  

On my system its working.  Let me know.

You can also uninstall the later require_all gem (v2.x.x) so you know your system isn't using it.

Thanks,
Eric

**Comment by BartokFan** [comment]
Thanks Eric.  I could not figure out how to dump this screen shot onto github.

As you can see I did download the latest version and uninstalled the other versions.

Still getting an error for require all.

Evan (Bartokfan)
